"""Schema guidance annotation, shared by every structured-output agent.

A schema generated by `model_json_schema()` states shape but not invariants: pydantic emits
a `title` per field and nothing else, so the wire sees `kind_detail: string | null` with no
hint that it must be null unless `kind` is `other`. Stating those rules only in the system
prompt demonstrably does not hold - measured against the live API on Day 4, every model
tested filled the `*_detail` fields regardless of the enum. The schema is where a model
looks hardest, so the rules belong on the fields they constrain.

This is annotation only: descriptions are added, no shape is touched, and `aioc.contracts`
stays untouched (the contract is frozen; these are prompt affordances rather than data).
`apply_guidance` fails at import time if a target field no longer exists, so renaming a
contract field breaks loudly here instead of silently dropping guidance a model depends on.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any

# Sentinel key for guidance that targets the top-level object rather than a `$defs` entry.
ROOT = "$root"


def apply_guidance(
    schema: dict[str, Any],
    *,
    name: str,
    description: str,
    guidance: dict[str, dict[str, str]],
) -> dict[str, Any]:
    """Attach invariant guidance to a generated schema, failing loudly on drift.

    ``guidance`` is keyed by `$defs` name (or `ROOT` for the top-level object), then by
    field name. ``name`` labels the drift error so the failing agent is identifiable.
    """
    annotated: dict[str, Any] = deepcopy(schema)
    annotated["description"] = description

    missing: list[str] = []
    for def_name, fields in guidance.items():
        target = annotated if def_name == ROOT else annotated.get("$defs", {}).get(def_name)
        properties = (target or {}).get("properties", {})
        for field, text in fields.items():
            if field not in properties:
                missing.append(f"{def_name}.{field}")
                continue
            # A `$ref` sibling is legal in JSON Schema 2020-12, so this works for plain
            # fields, `anyOf` unions, and `$ref`s alike.
            properties[field]["description"] = text

    if missing:
        raise RuntimeError(
            f"{name} schema guidance is out of sync with aioc.contracts; no such field: "
            + ", ".join(sorted(missing))
        )
    return annotated
